Add guard to handle twitch extension api requests
romanzipp/Laravel-Twitch pull request #130
Opened 2022-06-28 22:04 UTC by ghostzero

- Add extension guard for extensions
- Bump php support, since it's [not supported](https://www.php.net/supported-versions.php) anymore(including security updates)

2022-06-30 16:43 UTC, Katzen48 requested changes

2022-10-19 21:28 UTC, ghostzero commented
Seems to work now :D

2023-03-04 19:42 UTC, Katzen48 commented
Btw. I don't think the tests below PHP 8.0 are necessary.
Every version < PHP 8.0 don't even get security updates anymore and even PHP 8.0 is out of active support.

2023-03-09 17:27 UTC, romanzipp commented
To be honest I don't really understand which use case will be covered with adding an auth guard. Could you share an example?

2023-03-20 18:37 UTC, merged